// Roster Definitions
export const metsBlueRoster = [
  "Acosta, Cesar",
  "Terrero, Marcos",
  "Garcia, Keiver",
  "Semprun, Yorber",
  "Ubiera, Giomar",
  "Guerrero, Vladi",
  "Rivas, Yensi",
  "Eneas, Alexander",
  "Acosta, Alex",
  "Mella, Leandy",
  "Ramirez, Justin",
  "Sanchez, Jonnhan",
  "Cuello, Jhonael",
  "Rodriguez, Yovanny",
  "De Aza, Diover",
  "Francis, Hector",
];

export const metsOrangeRoster = [
  "Mindiola, Yeider",
  "Reyes, Josmir",
  "Garcia, Roni",
  "Herrera, Roybert",
  "Matos, Alvaro",
  "Padilla, Jose",
  "Pena, Elian",
  "Pinango, Fidel",
  "Miranda, Adolfo",
  "Rincon, Heriberto",
  "Rodriguez, Georwill",
  "Blanco, Aiberson",
  "Amparo, Yunior",
  "Silva, Adrian",
  "Larez, Cristopher",
];

// Weekly ranges
export const weekRangesEn = [
  { label: "Week One (6/16 - 6/21)", start: "06/16", end: "06/21" },
  { label: "Week Two (6/23 - 6/28)", start: "06/23", end: "06/28" },
  { label: "Week Three (6/30 - 7/05)", start: "06/30", end: "07/05" },
  { label: "Week Four (7/07 - 7/12)", start: "07/07", end: "07/12" },
  { label: "Week Five (7/14 - 7/19)", start: "07/14", end: "07/19" },
  { label: "Week Six (7/21 - 7/26)", start: "07/21", end: "07/26" },
  { label: "Week Seven (7/28 - 8/02)", start: "07/28", end: "08/02" },
  { label: "Week Eight (8/04 - 8/09)", start: "08/04", end: "08/09" },
  { label: "Week Nine (8/11 - 8/16)", start: "08/11", end: "08/16" },
  { label: "Week Ten (8/18 - 8/19)", start: "08/18", end: "08/19" },
];

export const weekRangesEs = [
  { label: "Semana Uno (6/16 - 6/21)", start: "06/16", end: "06/21" },
  { label: "Semana Dos (6/23 - 6/28)", start: "06/23", end: "06/28" },
  { label: "Semana Tres (6/30 - 7/05)", start: "06/30", end: "07/05" },
  { label: "Semana Cuatro (7/07 - 7/12)", start: "07/07", end: "07/12" },
  { label: "Semana Cinco (7/14 - 7/19)", start: "07/14", end: "07/19" },
  { label: "Semana Seis (7/21 - 7/26)", start: "07/21", end: "07/26" },
  { label: "Semana Siete (7/28 - 8/02)", start: "07/28", end: "08/02" },
  { label: "Semana Ocho (8/04 - 8/09)", start: "08/04", end: "08/09" },
  { label: "Semana Nueve (8/11 - 8/16)", start: "08/11", end: "08/16" },
  { label: "Semana Diez (8/18 - 8/19)", start: "08/18", end: "08/19" },
];

// Scoring point values
export const SCORING_POINTS = {
  xbh: 3,
  hard: 2,
  swing: 1,
  miss: -1,
  take: -3,
};

// Apple zone coordinates
export const APPLE_ZONE = {
  xMin: -0.56,
  xMax: 0.56,
  yMin: 1.833,
  yMax: 3.167,
};

// Locale translations
export const en = {
  title: "The Monster of the Middle",
  leaderboard: "Monster Leaderboard",
  uploadCsv: "Upload CSV",
  uploadedCsvs: "Uploaded CSVs",
  dataUpload: "Data Upload",
  previousCsv: "Previous CSV",
  loadedFiles: "Loaded Files",
  noFiles: "No CSV files loaded",
  xbh: "XBH",
  hard: "Hard Contact",
  swing: "Apple Swings",
  miss: "Apple Miss",
  take: "Apple Takes",
  opponent: "Opponent",
  pitchType: "Pitch Type",
  playResult: "Result",
  exitVelocity: "Exit Velocity",
  launchAngle: "Launch Angle",
  pitchVelocity: "Pitch Velocity",
  ivb: "IVB",
  hb: "HB",
  selectPlayer: "Select Player",
  allPlayers: "All Players",
  teamBlue: "Mets Blue",
  teamOrange: "Mets Orange",
  managePlayers: "Manage Players",
  selectWeek: "Select Week",
  allSeason: "Season Results",
  weeklyWinners: "Weekly Winners",
  cumulativeScore: "Cumulative Score",
  addPlayer: "Add Player",
  editPlayer: "Edit",
  deletePlayer: "Delete",
  playerName: "Player Name",
  save: "Save",
  cancel: "Cancel",
  unassigned: "Unassigned",
};

export const es = {
  title: "El Monstruo del Medio",
  leaderboard: "Tabla de Clasificación",
  uploadCsv: "Subir CSV",
  uploadedCsvs: "CSVs Subidos",
  dataUpload: "Carga de Datos",
  previousCsv: "CSV Anterior",
  loadedFiles: "Archivos Cargados",
  noFiles: "No hay archivos CSV cargados",
  xbh: "XBH",
  hard: "Contacto Fuerte",
  swing: "Swings en la Manzana",
  miss: "Fallo en la Manzana",
  take: "Toma en la Manzana",
  opponent: "Oponente",
  pitchType: "Tipo de Lanzamiento",
  playResult: "Resultado",
  exitVelocity: "Velocidad de Salida",
  launchAngle: "Ángulo de Salida",
  pitchVelocity: "Velocidad del Lanzamiento",
  ivb: "IVB",
  hb: "HB",
  selectPlayer: "Seleccionar Jugador",
  allPlayers: "Todos los Jugadores",
  teamBlue: "Mets Blue",
  teamOrange: "Mets Orange",
  managePlayers: "Gestionar Jugadores",
  selectWeek: "Seleccionar Semana",
  allSeason: "Resultados de Temporada",
  weeklyWinners: "Ganadores Semanales",
  cumulativeScore: "Puntuación Acumulativa",
  addPlayer: "Agregar Jugador",
  editPlayer: "Editar",
  deletePlayer: "Eliminar",
  playerName: "Nombre del Jugador",
  save: "Guardar",
  cancel: "Cancelar",
  unassigned: "Sin Asignar",
};

export const locales = { en, es };
